import type { NextPage } from 'next'
import Head from 'next/head'
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider
} from '@apollo/client';

import Banner from '../components/Banner';
import ClassSelectorScreen from '../screens/ClassSelectorScreen';

const client = new ApolloClient({
  uri: 'https://www.dnd5eapi.co/graphql',
  cache: new InMemoryCache()
});

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>DnD App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Banner/>
      <ApolloProvider client={client}>
        <ClassSelectorScreen/>
      </ApolloProvider>
    </div>
  )
}

export default Home
