import type { NextPage } from 'next'
import Head from 'next/head'
import styled from '@emotion/styled';

import ClassPage from './component/ClassPage';
import Banner from './component/Banner';

const Container = styled.div`
  margin: 24px;
`

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>DnD App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
      </Head>
      <Banner/>
      <Container>
        <ClassPage
          propClassList={[
            {
              className: 'Bard',
              classEndpoint: '/api/classes/bard',
              classHitDie: 8
            },
            {
              className: 'Barbarian',
              classEndpoint: '/api/classes/barbarian',
              classHitDie: 12
            }
          ]}
        />
      </Container>
    </div>
  )
}

export default Home
